version: '3'
volumes:
  dbdata:
  app:
  data:

services:
  gogsdb:
    image: postgres:9.5
    networks:
     - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
    env_file:
     - gogsdb.env
    volumes:
     - dbdata:/var/lib/postgresql/data

  gogs:
    image: gcavalcante8808/gogs
    build: .
    env_file:
     - gogs.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s
    networks:
     - default
    volumes:
     - data:/home/git/gogs-repositories
     - app:/home/git/gogs/custom
    ports:
     - "2220:2220"
     - "8080:80"
    depends_on:
     - gogsdb


networks:
  default:
    external: false
